[build]
  command = "npm run build" # Replace with your build command if necessary
  publish = "public" # Replace with your publish directory if necessary

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
